tenant:
  hostname: "fccipqa.int-aws-us.webmethods.io"   # webMethodsIO Integration hostname or ip address
  port: "443"                                       # webMethodsIO Integration port
  type: "dev"                                         #DEV
